# Site settings
title: Chowdown
email: edinel@solace.org
description: Eddie's Recipe Database.  Based on Chowhound- the plain text recipe database for hackers
baseurl: "https://recipes.solace.org"
language: "en"
lang_direction: "ltr"
color: "#007FFF"
twitter_username: t0rque
github_username:  edinel

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  components:
    output: true
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
